version: '3.0'
services:
  db:
    image: postgres
    container_name: postgrescontainer
    restart: always
    environment:
        - POSTGRES_PASSWORD=admin
        - POSTGRES_USER=root
        - POSTGRES_DB=wallet
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - wallet_network
  api:
    container_name: api
    depends_on: 
      - db
    image: jvitoralmeida/walletimage:1.0.11
    networks:
      - wallet_network
    ports:
      - 8080:8787
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - wallet_network
  frontend:
    build:
      context: ../
      dockerfile: Dockerfile
    image: docker_frontend:latest
    networks:
      - wallet_network
    ports:
    - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"        

volumes:
  db:
networks:
  wallet_network: